name: mimic
version: 1.1.0
summary: Mimic TTS engine
description:  Mycroft's TTS engine; a fork of  CMU's Flite (Festival Lite) 
confinement: strict
parts: 
  mimic:
    plugin: autotools
    configflags:
     - --enable-static=no
     - --prefix=/usr/local/
     - --with-audio=pulseaudio
    source: https://github.com/MycroftAI/mimic.git
    source-type: git
    build-packages:
      - libpulse-dev
      - gcc
      - make
      - pkg-config
      - libasound2-dev
    stage-packages: [libpulse0]
    snap:
      - usr/local/bin
      - usr/local/include
      - usr/local/lib
apps:
  mimic:
    command: usr/local/bin/mimic
    plugs: [pulseaudio]
